#!/bin/bash
# Configuration ULTRA minimale pour BusyBox rescue shell
# Seulement 27 applets essentiels

set -e

echo "Configuration ULTRA minimale pour rescue shell..."

# Repartir de zéro
make allnoconfig > /dev/null 2>&1

# Activer les options de base strictement nécessaires
cat >> .config << 'EOF'
CONFIG_HAVE_DOT_CONFIG=y
CONFIG_BUSYBOX=y
CONFIG_STATIC=y
CONFIG_LFS=y
CONFIG_LONG_OPTS=y
CONFIG_FEATURE_EDITING=y
CONFIG_FEATURE_EDITING_MAX_LEN=1024
CONFIG_FEATURE_TAB_COMPLETION=y
CONFIG_FEATURE_BUFFERS_USE_MALLOC=y
CONFIG_STACK_OPTIMIZATION_386=y
CONFIG_STATIC_LIBGCC=y
CONFIG_INSTALL_APPLET_SYMLINKS=y
CONFIG_PREFIX="./_install"
CONFIG_NO_DEBUG_LIB=y
CONFIG_TRY_LOOP_CONFIGURE=y

# Optimisations de taille
CONFIG_EXTRA_CFLAGS="-Os -ffunction-sections -fdata-sections -fno-asynchronous-unwind-tables"
CONFIG_EXTRA_LDFLAGS="-Wl,--gc-sections -Wl,--strip-all"

# Shell ASH minimal
CONFIG_SH_IS_ASH=y
CONFIG_BASH_IS_NONE=y
CONFIG_ASH=y
CONFIG_ASH_OPTIMIZE_FOR_SIZE=y
CONFIG_ASH_INTERNAL_GLOB=y
CONFIG_ASH_JOB_CONTROL=y
CONFIG_ASH_ECHO=y
CONFIG_ASH_PRINTF=y
CONFIG_ASH_TEST=y
CONFIG_FEATURE_SH_MATH=y

# Coreutils essentiels (27 applets)
CONFIG_LS=y
CONFIG_FEATURE_LS_FILETYPES=y
CONFIG_FEATURE_LS_FOLLOWLINKS=y
CONFIG_FEATURE_LS_RECURSIVE=y
CONFIG_FEATURE_LS_SORTFILES=y
CONFIG_FEATURE_LS_TIMESTAMPS=y
CONFIG_FEATURE_LS_USERNAME=y
CONFIG_FEATURE_LS_COLOR=y
CONFIG_CAT=y
CONFIG_ECHO=y
CONFIG_FEATURE_FANCY_ECHO=y
CONFIG_STAT=y
CONFIG_DF=y
CONFIG_FEATURE_DF_FANCY=y
CONFIG_TAIL=y
CONFIG_FEATURE_FANCY_TAIL=y
CONFIG_CP=y
CONFIG_MV=y
CONFIG_RM=y
CONFIG_MKDIR=y

# Recherche
CONFIG_FIND=y
CONFIG_FEATURE_FIND_PRINT0=y
CONFIG_FEATURE_FIND_MTIME=y
CONFIG_FEATURE_FIND_PERM=y
CONFIG_FEATURE_FIND_TYPE=y
CONFIG_FEATURE_FIND_XDEV=y
CONFIG_FEATURE_FIND_MAXDEPTH=y
CONFIG_FEATURE_FIND_NEWER=y
CONFIG_FEATURE_FIND_EXEC=y
CONFIG_FEATURE_FIND_USER=y
CONFIG_FEATURE_FIND_GROUP=y
CONFIG_FEATURE_FIND_NOT=y
CONFIG_FEATURE_FIND_DEPTH=y
CONFIG_FEATURE_FIND_PAREN=y
CONFIG_FEATURE_FIND_SIZE=y
CONFIG_FEATURE_FIND_PRUNE=y
CONFIG_FEATURE_FIND_DELETE=y
CONFIG_FEATURE_FIND_PATH=y
CONFIG_GREP=y
CONFIG_EGREP=y
CONFIG_FGREP=y
CONFIG_FEATURE_GREP_CONTEXT=y
CONFIG_XARGS=y
CONFIG_FEATURE_XARGS_SUPPORT_CONFIRMATION=y
CONFIG_FEATURE_XARGS_SUPPORT_QUOTES=y
CONFIG_FEATURE_XARGS_SUPPORT_TERMOPT=y
CONFIG_FEATURE_XARGS_SUPPORT_ZERO_TERM=y

# Éditeurs
CONFIG_SED=y
CONFIG_AWK=y
CONFIG_FEATURE_AWK_LIBM=y

# Système de fichiers
CONFIG_MOUNT=y
CONFIG_FEATURE_MOUNT_LABEL=y
CONFIG_FEATURE_MOUNT_FLAGS=y
CONFIG_FEATURE_MOUNT_FSTAB=y
CONFIG_FEATURE_MOUNT_LOOP=y
CONFIG_FEATURE_MOUNT_LOOP_CREATE=y
CONFIG_UMOUNT=y
CONFIG_FEATURE_UMOUNT_ALL=y
CONFIG_BLKID=y
CONFIG_FEATURE_BLKID_TYPE=y
CONFIG_LOSETUP=y

# Support filesystem types
CONFIG_FEATURE_VOLUMEID_EXT=y
CONFIG_FEATURE_VOLUMEID_FAT=y
CONFIG_FEATURE_VOLUMEID_NTFS=y
CONFIG_FEATURE_VOLUMEID_ISO9660=y
CONFIG_FEATURE_VOLUMEID_LINUXSWAP=y

# Process management
CONFIG_PS=y
CONFIG_KILL=y

# Diagnostic
CONFIG_DMESG=y
CONFIG_UNAME=y
CONFIG_UNAME_OSNAME="GNU/Linux"

# Inspection binaire
CONFIG_HEXDUMP=y
CONFIG_HD=y

# Réseau
CONFIG_IFCONFIG=y
CONFIG_FEATURE_IFCONFIG_STATUS=y
CONFIG_FEATURE_IFCONFIG_HW=y
CONFIG_FEATURE_IFCONFIG_BROADCAST_PLUS=y
CONFIG_IP=y
CONFIG_IPADDR=y
CONFIG_IPLINK=y
CONFIG_IPROUTE=y
CONFIG_IPTUNNEL=y
CONFIG_IPRULE=y
CONFIG_IPNEIGH=y
CONFIG_FEATURE_IP_ADDRESS=y
CONFIG_FEATURE_IP_LINK=y
CONFIG_FEATURE_IP_ROUTE=y
CONFIG_FEATURE_IP_ROUTE_DIR="/etc/iproute2"
CONFIG_FEATURE_IP_TUNNEL=y
CONFIG_FEATURE_IP_RULE=y
CONFIG_FEATURE_IP_NEIGH=y
CONFIG_PING=y
CONFIG_FEATURE_FANCY_PING=y
EOF

echo "Validation de la configuration..."
yes "" | make oldconfig > /dev/null 2>&1

echo "Configuration ULTRA minimale appliquée!"
echo "Applets activés:"
./busybox --list 2>/dev/null | wc -l || echo "Binaire pas encore compilé"

# Made with Bob
